# Generated by Django 5.1.1 on 2024-10-09 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_email', models.EmailField(max_length=254, unique=True)),
                ('business_address', models.CharField(max_length=255)),
                ('business_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('trade_category', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('staff_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('listing_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('trade_category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employer')),
            ],
        ),
        migrations.CreateModel(
            name='JobRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_to_work', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.joblisting')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.staffregister')),
            ],
        ),
    ]
